import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageType = 'EN' | 'ID';

export const translations = {
  EN: {
    // Nav & Common
    dashboard: "Dashboard",
    storyBible: "Story Bible",
    characters: "Characters",
    episodesArchive: "Episodes Archive",
    promptBuilder: "Prompt Builder",
    generator: "Generator",
    logsConsole: "Logs Console",
    settings: "Settings",
    runGenerator: "RUN GENERATOR",
    sessionOperator: "Session Operator",
    apiLatency: "API Latency",
    database: "Database",
    autoSave: "Auto-Save",
    enabled: "Enabled",
    online: "Online",
    processingPipeline: "Processing Pipeline...",
    provider: "Provider",
    
    // Dashboard
    welcomeBack: "Welcome back, Operator",
    tagline: "Your autonomous novel writing pipeline is fully operational.",
    episodesDrafted: "Episodes Drafted",
    activeCast: "Active Cast",
    bibleRules: "Story Bible Rules",
    lastLogAction: "Last Log Action",
    recentActivityLogs: "Recent Activity Logs",
    quickActions: "Quick Actions Pipeline",
    manualGenerateNow: "Manual Generate Now",
    manualGenerateNowDesc: "Initiate the automated model writing loop, compile current story bible settings, and produce the next chapter draft.",
    runEngine: "RUN ENGINE",
    generating: "GENERATING...",
    generatorConfig: "Generator Configuration",
    generateNow: "Generate Now",
    latestProseReport: "LATEST PROSE REPORT",
    noChaptersWritten: "No chapters written",
    noActiveDrafts: "No active drafts are compiled in your localized workspace database.",
    viewArchive: "VIEW ARCHIVE",
    workspaceDataSync: "WORKSPACE DATA SYNC",
    syncStorageSettings: "Sync Storage & Settings",
    syncing: "SYNCING...",
    synced: "SYNCED",
    syncDescActive: "Pushing latest casting sheets, prose chapters, and bible guidelines to backup destinations...",
    syncDescSuccess: "Synchronization complete. Drive backup updated successfully.",
    syncDescDefault: "Manually force schema validation and synchronize prompt templates across all active providers.",
    syncRepository: "SYNC REPOSITORY",
    systemOverview: "System Overview",
    currentActiveProseDraft: "Current Active Prose Draft",
    viewLatestDraftDetails: "View the latest draft and edit prose details inside the archive panel.",
    noLogsToDisplay: "No active console telemetry logs to display.",

    // Story Bible
    bibleTitle: "Story Bible Workspace",
    bibleSubtitle: "Establish core narrative directives, stylistic rules, universe settings, and forbidden vocabulary constraint blocks.",
    genre: "Genre",
    universeName: "Universe Name",
    storyStyle: "Writing / Prose Style",
    narratorStyle: "Narrator Style",
    language: "Language",
    tone: "Story Tone",
    writingRules: "Critical Writing & Prose Directives",
    promptRules: "Prompt Synthesis & Formatting Rules",
    forbiddenRules: "Forbidden Patterns & Vocabulary",
    customInstructions: "Custom AI System Instructions",
    episodeLength: "Target Episode Length (Words)",
    saveBibleSettings: "Save Bible Settings",
    biblePlaceholderGenre: "e.g., Cyberpunk, Dark Fantasy",
    biblePlaceholderUniverse: "e.g., Neo-Tokyo 2099",
    biblePlaceholderStyle: "e.g., Atmospheric, cinematic, limited third-person perspective",
    biblePlaceholderNarrator: "e.g., Third-Person Limited (focusing on Jax)",
    biblePlaceholderLanguage: "e.g., English, Indonesian, Bilingual",
    biblePlaceholderTone: "e.g., Gritty, melancholic, noir",
    biblePlaceholderWritingRules: "Rules for writing prose, scene transition guidelines...",
    biblePlaceholderPromptRules: "Specific structural prompts, pacing and output guidelines...",
    biblePlaceholderForbiddenRules: "Banned words, clichés, repetitive structures...",
    biblePlaceholderCustom: "Any special customized system instructions...",

    // Characters
    charactersDatabase: "Character Casting Database",
    charactersSubtitle: "Manage the active cast of your universe, define relationships, biographies, and track status.",
    addCharacter: "Add New Character",
    editCharacter: "Edit Character Profile",
    noCharacters: "No characters registered in this universe database. Add a character to begin casting.",
    charName: "Character Name",
    charAge: "Age",
    charGender: "Gender",
    charOccupation: "Occupation",
    charPersonality: "Personality Archetype",
    charStatus: "Status",
    charRelationships: "Relationships & Ties",
    charBiography: "Biography & Background",
    charLocation: "Primary Location / Affiliation",
    charNotes: "Casting & Character Notes",
    alive: "Alive",
    dead: "Dead",
    saveCharacter: "Save Character Profile",
    deleteCharacter: "Delete Character",
    confirmDeleteChar: "Are you sure you want to delete this character?",
    relationshipNetwork: "Relationship Network",
    relationshipNetworkDesc: "Explore and manage character ties, conflicts, and narratives through interactive graph visualization.",
    statusActive: "Active Node",
    relatedCharacters: "Related Characters",
    searchPlaceholder: "Search characters...",
    resetGraph: "Reset Simulation",
    noRelationshipsFound: "No narrative relationships identified. Fill in the 'Relationships & Ties' field of your characters to synchronize connections automatically!",

    // Episodes Archive
    archiveTitle: "Episodes Draft Archive",
    archiveSubtitle: "Review, edit, and dispatch generated drafts. Coordinate manual deliveries to Email & Google Drive.",
    filterStatus: "Filter Status",
    allDrafts: "All Drafts",
    published: "Published",
    draft: "Draft",
    noEpisodes: "No episodes compiled in the archive yet. Run the story generator to produce your first draft.",
    unsavedBackupDetected: "Unsaved Browser Backup Detected",
    backupDesc: "A newer, unsaved draft of this episode was saved to your browser's local storage. Would you like to restore it?",
    restoreDraft: "Restore Draft",
    dismiss: "Dismiss",
    editorMetadata: "Editor Metadata",
    wordCount: "Word Count",
    words: "words",
    aiProviderAndModel: "AI Provider & Model",
    promptUsed: "Prompt Synthesis Used",
    saveChanges: "Save Changes",
    deliverToDestinations: "Deliver to Backup Destinations",
    deliverNow: "Deliver Now",
    delivering: "Delivering...",
    deliverySuccess: "Delivery Dispatched Successfully",
    deliveryFail: "Delivery Dispatch Failed",
    deleteEpisode: "Delete Episode",
    confirmDeleteEp: "Are you sure you want to permanently delete this episode from the database archive?",

    // Prompt Builder
    builderTitle: "Prompt Synthesis Builder",
    builderSubtitle: "Review generated prompts, test formatting rules, and copy prompts to feed your local AI pipeline.",
    promptPresets: "Narrator Prompt Presets",
    selectPresetDesc: "Select a story direction preset to automatically pre-populate the Generator direction container.",
    promptDirection: "Snippet / Prompt Direction",
    targetLength: "Target Word Length",
    customDirection: "Custom Direction",
    buildPromptPreview: "Build Prompt Preview",
    systemPromptTitle: "Synthesized System Prompt",
    userPromptTitle: "Synthesized User Prompt",
    copyPrompt: "Copy System Prompt",
    copyUserPrompt: "Copy User Prompt",

    // Generator Workspace
    generatorTitle: "Story Generator Workspace",
    generatorSubtitle: "Trigger the autonomous AI writing loop, oversee background compilation steppers, and monitor log outputs.",
    pipelineStepsTitle: "Active Production Steppers",
    runStoryEngine: "RUN STORY ENGINE",
    activeLogTelemetry: "Active Log Telemetry Stream",
    logFilterAll: "All Logs",
    logFilterInfo: "Info",
    logFilterWarn: "Warning",
    logFilterErr: "Error",
    clearLogs: "Clear Logs Console",
    refreshLogs: "Refresh Logs",
    logsTitle: "System Logs Console",
    logsSubtitle: "Inspect background telemetry logs, pipeline steps, and automated background scheduler outputs.",

    // Settings
    settingsTitle: "System Settings & Integration",
    settingsSubtitle: "Configure API access keys, automated backup SMTP credentials, and scheduled run configurations.",
    aiProviderConfig: "AI Model Provider Configuration",
    smtpConfig: "SMTP Email Delivery Configuration",
    driveConfig: "Google Drive Output Directory Configuration",
    schedulerConfig: "Autonomous Scheduler Configuration",
    backupCenter: "Browser Local Storage Backup Center",
    backupCenterDesc: "Manage localized backup files. You can snapshot the entire system state (Story Bible, Character Cast, Episodes Archive, and configurations) directly to your browser's secure localStorage container, instantly restore snapshots to the active system server, or export a physical JSON backup.",
    backupOutputToLocalStorage: "Backup Output to LocalStorage",
    restoreDbFromLocalStorage: "Restore DB from LocalStorage",
    downloadPortableJson: "Download Portable JSON File",
    activeBackupFound: "ACTIVE BACKUP FOUND",
    noBackupStored: "NO BACKUP STORED",
    confirmRestoreDb: "Are you sure you want to restore the entire database from your browser local storage? This will overwrite your current settings, character sheets, and episodes archive.",
    confirmClearLogs: "Are you sure you want to clear all logs?",
    engineConfig: "Engine Configuration",
    storageConfig: "Storage Configuration",
    backupOutput: "Backup Output",
    restoreBackup: "Restore Backup",
    downloadBackupFile: "Download Backup File",
    newProject: "New Project",
    projectNamePlaceholder: "e.g., Cyberpunk Heist",
    projectsArchive: "Stories Archive",
    activeProject: "Active Project",
    createNewStory: "Create New Story Title",
    create: "Create",
    cancel: "Cancel",
    switchProject: "Switch Project",
    projectTitleRequired: "Project title is required.",
    existingProjects: "Archived Stories",
    emptyArchive: "No archived projects yet.",
    storyTitle: "Story Title",
    confirmDeleteProject: "Are you sure you want to delete this archived project? All associated character sheets and episode drafts for this story will be permanently lost."
  },
  ID: {
    // Nav & Common
    dashboard: "Dasbor",
    storyBible: "Alkitab Cerita",
    characters: "Karakter",
    episodesArchive: "Arsip Episode",
    promptBuilder: "Pembuat Prompt",
    generator: "Generator",
    logsConsole: "Konsol Log",
    settings: "Pengaturan",
    runGenerator: "JALANKAN GENERATOR",
    sessionOperator: "Operator Sesi",
    apiLatency: "Latensi API",
    database: "Basis Data",
    autoSave: "Simpan Otomatis",
    enabled: "Aktif",
    online: "Online",
    processingPipeline: "Memproses Saluran...",
    provider: "Penyedia",

    // Dashboard
    welcomeBack: "Selamat datang kembali, Operator",
    tagline: "Saluran penulisan novel otonom Anda sepenuhnya beroperasi.",
    episodesDrafted: "Draf Episode",
    activeCast: "Pemeran Aktif",
    bibleRules: "Aturan Alkitab Cerita",
    lastLogAction: "Aktivitas Log Terakhir",
    recentActivityLogs: "Log Aktivitas Terbaru",
    quickActions: "Saluran Tindakan Cepat",
    manualGenerateNow: "Hasilkan Manual Sekarang",
    manualGenerateNowDesc: "Mulai putaran penulisan model otomatis, kompilasi pengaturan alkitab cerita saat ini, dan hasilkan draf bab berikutnya.",
    runEngine: "JALANKAN MESIN",
    generating: "MENGHASILKAN...",
    latestProseReport: "LAPORAN PROSA TERBARU",
    noChaptersWritten: "Belum ada bab yang ditulis",
    noActiveDrafts: "Tidak ada draf aktif yang dikompilasi dalam basis data ruang kerja lokal Anda.",
    viewArchive: "LIHAT ARSIP",
    workspaceDataSync: "SINKRONISASI DATA RUANG KERJA",
    syncStorageSettings: "Sinkronisasi Penyimpanan & Pengaturan",
    syncing: "MENYINKRONKAN...",
    synced: "TERSINKRONISASI",
    syncDescActive: "Mengirimkan lembar karakter terbaru, bab prosa, dan panduan cerita ke tujuan cadangan...",
    syncDescSuccess: "Sinkronisasi selesai. Cadangan Google Drive berhasil diperbarui.",
    syncDescDefault: "Paksa validasi skema secara manual dan sinkronkan templat prompt di semua penyedia aktif.",
    syncRepository: "SINKRONKAN REPOSITORI",
    systemOverview: "Ikhtisar Sistem",
    currentActiveProseDraft: "Draf Prosa Aktif Saat Ini",
    viewLatestDraftDetails: "Lihat draf terbaru dan edit detail prosa di dalam panel arsip.",
    noLogsToDisplay: "Tidak ada log telemetri konsol aktif untuk ditampilkan.",

    // Story Bible
    bibleTitle: "Ruang Kerja Alkitab Cerita",
    bibleSubtitle: "Tetapkan arahan naratif inti, aturan gaya, pengaturan alam semesta, dan blok batasan kosakata yang dilarang.",
    genre: "Genre / Aliran",
    universeName: "Nama Semesta",
    storyStyle: "Gaya Penulisan / Prosa",
    narratorStyle: "Gaya Narator",
    language: "Bahasa",
    tone: "Nada Cerita",
    writingRules: "Arahan Penulisan & Prosa Kritis",
    promptRules: "Aturan Sintesis & Pemformatan Prompt",
    forbiddenRules: "Pola & Kosakata yang Dilarang",
    customInstructions: "Instruksi Sistem AI Kustom",
    episodeLength: "Panjang Episode Target (Kata)",
    saveBibleSettings: "Simpan Pengaturan Alkitab",
    biblePlaceholderGenre: "mis., Cyberpunk, Fantasi Gelap",
    biblePlaceholderUniverse: "mis., Neo-Tokyo 2099",
    biblePlaceholderStyle: "mis., Atmosferik, sinematik, sudut pandang orang ketiga terbatas",
    biblePlaceholderNarrator: "mis., Orang Ketiga Terbatas (fokus pada Jax)",
    biblePlaceholderLanguage: "mis., Inggris, Indonesia, Dwibahasa",
    biblePlaceholderTone: "mis., Kelam, melankolis, noir",
    biblePlaceholderWritingRules: "Aturan untuk menulis prosa, panduan transisi adegan...",
    biblePlaceholderPromptRules: "Prompt struktural khusus, panduan ritme dan hasil...",
    biblePlaceholderForbiddenRules: "Kata-kata yang dilarang, klise, struktur berulang...",
    biblePlaceholderCustom: "Instruksi sistem khusus yang disesuaikan...",

    // Characters
    charactersDatabase: "Basis Data Pemeran Karakter",
    charactersSubtitle: "Kelola pemeran aktif semesta Anda, tentukan hubungan, biografi, dan lacak status.",
    addCharacter: "Tambah Karakter Baru",
    editCharacter: "Edit Profil Karakter",
    noCharacters: "Tidak ada karakter yang terdaftar dalam basis data semesta ini. Tambahkan karakter untuk memulai.",
    charName: "Nama Karakter",
    charAge: "Usia",
    charGender: "Jenis Kelamin",
    charOccupation: "Pekerjaan",
    charPersonality: "Arketipe Kepribadian",
    charStatus: "Status",
    charRelationships: "Hubungan & Ikatan",
    charBiography: "Biografi & Latar Belakang",
    charLocation: "Lokasi Utama / Afiliasi",
    charNotes: "Catatan Karakter & Casting",
    alive: "Hidup",
    dead: "Meninggal",
    saveCharacter: "Simpan Profil Karakter",
    deleteCharacter: "Hapus Karakter",
    confirmDeleteChar: "Apakah Anda yakin ingin menghapus karakter ini?",
    relationshipNetwork: "Jejaring Hubungan",
    relationshipNetworkDesc: "Jelajahi dan kelola ikatan, konflik, dan narasi karakter melalui visualisasi grafis interaktif.",
    statusActive: "Simpul Aktif",
    relatedCharacters: "Karakter Terkait",
    searchPlaceholder: "Cari karakter...",
    resetGraph: "Atur Ulang Simulasi",
    noRelationshipsFound: "Tidak ada hubungan narasi yang diidentifikasi. Isi bidang 'Hubungan & Ikatan' karakter Anda untuk menyinkronkan koneksi secara otomatis!",

    // Episodes Archive
    archiveTitle: "Arsip Draf Episode",
    archiveSubtitle: "Tinjau, edit, dan kirim draf yang dihasilkan. Koordinasikan pengiriman manual ke Email & Google Drive.",
    filterStatus: "Saring Status",
    allDrafts: "Semua Draf",
    published: "Diterbitkan",
    draft: "Draf",
    noEpisodes: "Belum ada episode yang disusun dalam arsip. Jalankan generator cerita untuk menghasilkan draf pertama Anda.",
    unsavedBackupDetected: "Cadangan Browser Tidak Tersimpan Terdeteksi",
    backupDesc: "Draf yang lebih baru dan belum tersimpan dari episode ini disimpan di penyimpanan lokal browser Anda. Apakah Anda ingin memulihkannya?",
    restoreDraft: "Pulihkan Draf",
    dismiss: "Abaikan",
    editorMetadata: "Metadata Editor",
    wordCount: "Jumlah Kata",
    words: "kata",
    aiProviderAndModel: "Penyedia & Model AI",
    promptUsed: "Sintesis Prompt yang Digunakan",
    saveChanges: "Simpan Perubahan",
    deliverToDestinations: "Kirim ke Tujuan Cadangan",
    deliverNow: "Kirim Sekarang",
    delivering: "Mengirim...",
    deliverySuccess: "Pengiriman Berhasil Dikirim",
    deliveryFail: "Pengiriman Gagal Dikirim",
    deleteEpisode: "Hapus Episode",
    confirmDeleteEp: "Apakah Anda yakin ingin menghapus episode ini secara permanen dari arsip basis data?",

    // Prompt Builder
    builderTitle: "Pembuat Sintesis Prompt",
    builderSubtitle: "Tinjau prompt yang dihasilkan, uji aturan pemformatan, dan salin prompt untuk dimasukkan ke saluran AI lokal Anda.",
    promptPresets: "Preset Prompt Narator",
    selectPresetDesc: "Pilih preset arah cerita untuk secara otomatis mengisi wadah arah Generator.",
    promptDirection: "Potongan / Arah Prompt",
    targetLength: "Target Panjang Kata",
    customDirection: "Arah Kustom",
    buildPromptPreview: "Pratinjau Hasil Prompt",
    systemPromptTitle: "Prompt Sistem yang Disintesis",
    userPromptTitle: "Prompt Pengguna yang Disintesis",
    copyPrompt: "Salin Prompt Sistem",
    copyUserPrompt: "Salin Prompt Pengguna",

    // Generator Workspace
    generatorTitle: "Ruang Kerja Generator Cerita",
    generatorSubtitle: "Jalankan putaran penulisan AI otonom, awasi langkah kompilasi latar belakang, dan pantau keluaran log.",
    pipelineStepsTitle: "Langkah Produksi Aktif",
    runStoryEngine: "JALANKAN MESIN CERITA",
    activeLogTelemetry: "Aliran Telemetri Log Aktif",
    logFilterAll: "Semua Log",
    logFilterInfo: "Info",
    logFilterWarn: "Peringatan",
    logFilterErr: "Kesalahan",
    clearLogs: "Bersihkan Konsol Log",
    refreshLogs: "Segarkan Log",
    logsTitle: "Konsol Log Sistem",
    logsSubtitle: "Periksa log telemetri latar belakang, langkah-langkah saluran, dan keluaran penjadwal latar belakang otomatis.",

    // Settings
    settingsTitle: "Pengaturan Sistem & Integrasi",
    settingsSubtitle: "Konfigurasikan kunci akses API, kredensial SMTP cadangan otomatis, dan konfigurasi jalankan terjadwal.",
    aiProviderConfig: "Konfigurasi Penyedia Model AI",
    smtpConfig: "Konfigurasi Pengiriman Email SMTP",
    driveConfig: "Konfigurasi Direktori Keluaran Google Drive",
    schedulerConfig: "Konfigurasi Penjadwal Otonom",
    backupCenter: "Pusat Cadangan Penyimpanan Lokal Browser",
    backupCenterDesc: "Kelola file cadangan lokal. Anda dapat membuat snapshot dari seluruh status sistem (Alkitab Cerita, Karakter, Arsip Episode, dan konfigurasi) langsung ke penyimpanan lokal browser Anda, memulihkan snapshot secara instan ke server aktif, atau mengunduh cadangan JSON fisik.",
    backupOutputToLocalStorage: "Cadangkan Output ke LocalStorage",
    restoreDbFromLocalStorage: "Pulihkan DB dari LocalStorage",
    downloadPortableJson: "Unduh File JSON Portabel",
    activeBackupFound: "CADANGAN AKTIF DITEMUKAN",
    noBackupStored: "TIDAK ADA CADANGAN TERSIMPAN",
    confirmRestoreDb: "Apakah Anda yakin ingin memulihkan seluruh basis data dari penyimpanan lokal browser Anda? Ini akan menimpa pengaturan, lembar karakter, dan arsip episode saat ini.",
    newProject: "Proyek Baru",
    projectNamePlaceholder: "mis., Pencurian Cyberpunk",
    projectsArchive: "Arsip Cerita",
    activeProject: "Proyek Aktif",
    createNewStory: "Buat Judul Cerita Baru",
    create: "Buat",
    cancel: "Batal",
    switchProject: "Ganti Proyek",
    projectTitleRequired: "Judul proyek harus diisi.",
    existingProjects: "Cerita Terarsip",
    emptyArchive: "Belum ada proyek terarsip.",
    storyTitle: "Judul Cerita",
    confirmDeleteProject: "Apakah Anda yakin ingin menghapus proyek terarsip ini? Semua lembar karakter dan draf episode terkait untuk cerita ini akan hilang secara permanen."
  }
};

interface LanguageContextProps {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (key: keyof typeof translations.EN) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageType>(() => {
    const saved = localStorage.getItem('fastory_ui_language');
    return (saved === 'ID' ? 'ID' : 'EN') as LanguageType;
  });

  const setLanguage = (lang: LanguageType) => {
    setLanguageState(lang);
    localStorage.setItem('fastory_ui_language', lang);
  };

  const t = (key: keyof typeof translations.EN): string => {
    return translations[language][key] || translations['EN'][key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
